name: ${PROJECT_NAME:-docker-vagrant}

services:
  master:
    container_name: kube-controller
    image: mayarun/docker-kube-controller:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VM_NODE_TYPE: master
      secrets:
        - ssh_username
        - ssh_password
    ports:
      - 2202:22
    networks:
      docker-vms:
        ipv4_address: 172.28.0.2

  worker-1:
    container_name: worker-node-1
    image: mayarun/docker-kube-worker-1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VM_NODE_TYPE: worker_1
    ports:
      - 2203:22
    networks:
      docker-vms:
        ipv4_address: 172.28.0.3
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip

  worker-2:
    container_name: worker-node-2
    image: mayarun/docker-kube-worker-2
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VM_NODE_TYPE: worker_2
    ports:
      - 2204:22
    networks:
      docker-vms:
        ipv4_address: 172.28.0.4

networks:
  docker-vms:
    name: docker-vms
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.0.1

secrets:
  ssh_username:
    environment: SSH_USERNAME
  ssh_password:
    file: secrets/ssh_password.txt
