name: mariadb-server

services:
  db:
    container_name: io.mayarun.mariadb
    image: mayarun/mariadb:latest
    restart: always
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root-pass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress-pass
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
