name: mariadb-server

services:
  db:
    container_name: mariadb
    image: mayarun/mariadb:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: administator
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
